name: Run all extension tasks

on:
  workflow_call:

jobs:
  create-matrix:
    uses: ./.github/workflows/matrix.yml

  test-master:
    needs: create-matrix
    uses: ./.github/workflows/test.yml
    with:
      matrix-json: ${{ needs.create-matrix.outputs.master_matrix }}

  test-stable:
    needs: create-matrix
    uses: ./.github/workflows/test.yml
    with:
      matrix-json: ${{ needs.create-matrix.outputs.stable_matrix }}

  code-style:
    uses: ./.github/workflows/cs.yml

  auto-fix:
    needs: create-matrix
    uses: ./.github/workflows/autofix.yml
    with:
      rector-php: ${{ needs.create-matrix.outputs.minphp }}
