name: PHP Code Style

on: [ workflow_call ]

jobs:
  phpcs:
    name: PHP CodeSniffer
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, intl, PDO, pdo_sqlite, bz2
          tools: cs2pr, phpcs

      - name: Create DokuWiki Environment
        id: dokuwiki-env
        uses: splitbrain/dokuwiki-gh-action@main
        with:
          branch: master

      - name: Run PHP codesniffer
        run: phpcs -q  --standard=_test/phpcs.xml --runtime-set ignore_warnings_on_exit 1 --report=checkstyle ${{ steps.dokuwiki-env.outputs.dir }} | cs2pr
