name: Run Extension Unit Tests

on:
  workflow_call:
    inputs:
      matrix-json:
        description: 'The matrix configuration as JSON. Need to supply arrays `php-version` and `dokuwiki-branch`.'
        required: true
        type: string
        default: '{"php-version": ["7.4", "8.0", "8.1", "8.2"], "dokuwiki-branch": ["master", "stable"]}'

jobs:
  test:
    name: PHP ${{ matrix.php-versions }} DokuWiki ${{ matrix.dokuwiki-branch }}
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    strategy:
      matrix: ${{ fromJson(inputs.matrix-json) }}
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, PDO, pdo_sqlite, bz2

      - name: Setup problem matchers
        run: |
          echo ::add-matcher::${{ runner.tool_cache }}/php.json
          echo ::add-matcher::${{ runner.tool_cache }}/phpunit.json

      - name: Create DokuWiki Environment
        id: dokuwiki-env
        uses: splitbrain/dokuwiki-gh-action@main
        with:
          branch: ${{ matrix.dokuwiki-branch }}

      - name: Setup PHPUnit
        run: |
          php _test/fetchphpunit.php
          cd _test

      - name: Run PHPUnit
        run: |
          cd _test
          php phpunit.phar --verbose --stderr --group ${{ steps.dokuwiki-env.outputs.type }}_${{ steps.dokuwiki-env.outputs.base }}
